name: ci
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install redis
        run: sudo apt-get install redis-server
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: test & lint
        # run: make test lint
        run: make test
      - name: Send coverage
        if: always()
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: make send-cover
